version: '3'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:80
    depends_on:
      - api
  api:
    container_name: api
    build: ./api
    volumes:
      - ./api:/usr/src/app
    external_links:
      - mongo
    depends_on:
      - mongo
    ports:
      - '8080:8080'
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
